# Generated by Django 5.0.7 on 2024-08-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_youtubevideo1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeVideo1',
        ),
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='title',
            new_name='name',
        ),
    ]
