# Generated by Django 5.0.7 on 2024-08-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_youtubevideo1_rename_url_youtubevideo_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
            preserve_default=False,
        ),
    ]
