# Generated by Django 5.0.7 on 2024-08-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_post_video_videopost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
